import { StyleSheet, Platform } from 'react-native';
import { colors } from '@/constants/colors';
import { typography } from '@/constants/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16, // Only left/right padding
    paddingTop: 8, // Minimal top padding
    paddingBottom: 16, // Bottom padding
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  greeting: {
    ...typography.h1,
    color: colors.white,
  },
  date: {
    ...typography.body,
    color: colors.lightGray,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
    minHeight: 200,
  },
  loadingText: {
    ...typography.body,
    color: colors.lightGray,
    marginTop: 16,
  },
  emptyState: {
    padding: 24,
    alignItems: 'center',
    marginTop: 40,
  },
  emptyTitle: {
    ...typography.h2,
    color: colors.white,
    marginBottom: 8,
  },
  emptyText: {
    ...typography.body,
    color: colors.lightGray,
    textAlign: 'center',
  },
  bannerButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bannerButtonText: {
    ...typography.bodySmall,
    color: colors.white,
  },

  // Next Workout Styles
  todaysWorkout: {
    marginBottom: 24,
  },
  nextWorkoutBadge: {
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    alignSelf: 'stretch',
    marginBottom: 16,
  },
  nextWorkoutBadgeText: {
    ...typography.caption,
    color: colors.black,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  sectionHeaderRow: {
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  linkText: {
    ...typography.bodySmall,
    color: colors.primary,
  },
  sectionTitle: {
    ...typography.h2,
    color: colors.white,
    marginBottom: 16,
  },
  workoutCard: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  workoutGradient: {
    paddingHorizontal: 0,
    paddingBottom: 20,
    paddingTop: 0,
  },
  workoutHeader: {
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  workoutName: {
    ...typography.h3,
    color: colors.white,
    fontSize: 22,
    fontWeight: 'bold',
    flex: 1,
    marginBottom: 12,
  },
  thumbnailsContainer: {
    marginBottom: 12,
  },
  thumbnailsContent: {
    gap: 8,
  },
  thumbnailWrapper: {
    width: 80,
    height: 80,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: colors.darkGray,
    position: 'relative',
  },
  thumbnailLoader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 2,
  },
  exerciseThumbnail: {
    width: '100%',
    height: '100%',
  },
  workoutMeta: {
    ...typography.body,
    color: colors.lightGray,
    fontSize: 14,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 20,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 6,
    gap: 4,
  },
  actionButtonText: {
    ...typography.caption,
    color: colors.white,
    fontSize: 11,
    fontWeight: '600',
  },
  actionButtonDisabled: {
    backgroundColor: colors.darkGray,
    opacity: 0.5,
  },
  alternativeWorkoutsSection: {
    marginBottom: 24,
  },
  alternativeWorkoutsTitle: {
    ...typography.h3,
    color: colors.white,
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  alternativeWorkoutsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  alternativeCard: {
    flex: 1,
    backgroundColor: colors.darkGray,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 140,
  },
  alternativeCardDisabled: {
    opacity: 0.4,
  },
  alternativeIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  alternativeCardTitle: {
    ...typography.body,
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  alternativeCardSubtitle: {
    ...typography.caption,
    color: colors.lightGray,
    fontSize: 11,
    textAlign: 'center',
  },
  workoutsNavigationSection: {
    marginBottom: 24,
  },
  workoutsNavigationRow: {
    flexDirection: 'row',
    gap: 12,
  },
  workoutNavCard: {
    flex: 1,
    backgroundColor: colors.darkGray,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    minHeight: 140,
  },
  workoutNavIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  workoutNavCardTitle: {
    ...typography.body,
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
    textAlign: 'center',
  },
  workoutNavCardSubtitle: {
    ...typography.caption,
    color: colors.lightGray,
    fontSize: 11,
    textAlign: 'center',
  },
  loadingWorkoutName: {
    height: 28,
    width: '70%',
    backgroundColor: colors.mediumGray,
    borderRadius: 6,
    opacity: 0.5,
  },
  workoutDuration: {
    ...typography.bodySmall,
    color: colors.white,
    opacity: 0.8,
  },
  exercisePreview: {
    marginBottom: 20,
  },
  exercisePreviewTitle: {
    ...typography.bodySmall,
    color: colors.white,
    marginBottom: 8,
    opacity: 0.9,
  },
  exercisePreviewItem: {
    ...typography.bodySmall,
    color: colors.white,
    marginBottom: 4,
    opacity: 0.8,
  },
  exercisePreviewMore: {
    ...typography.bodySmall,
    color: colors.white,
    fontStyle: 'italic',
    opacity: 0.7,
    marginTop: 4,
  },
  startWorkoutButtonContainer: {
    borderRadius: 12,
    overflow: 'hidden',
    marginHorizontal: 20,
  },
  startWorkoutButton: {
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    minHeight: 54,
  },
  startWorkoutText: {
    ...typography.button,
    color: colors.black,
    fontWeight: 'bold',
  },
  availabilitySubtext: {
    ...typography.bodySmall,
    color: colors.black,
    opacity: 0.8,
    fontSize: 12,
    marginTop: 2,
  },
  unavailableButtonContent: {
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    width: '100%',
    maxWidth: 400,
  },
  infoModalContent: {
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
  },
  infoModalTitle: {
    ...typography.h2,
    color: colors.white,
    marginBottom: 12,
    textAlign: 'center',
  },
  infoModalDescription: {
    ...typography.body,
    color: colors.lightGray,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 20,
  },
  infoModalButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 8,
  },
  infoModalButtonText: {
    ...typography.button,
    color: colors.black,
    fontWeight: 'bold',
  },
  comingSoonModalContent: {
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
  },
  comingSoonIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(138, 43, 226, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  comingSoonTitle: {
    ...typography.h2,
    color: colors.white,
    marginBottom: 12,
    textAlign: 'center',
    fontSize: 28,
    fontWeight: '700',
  },
  comingSoonDescription: {
    ...typography.body,
    color: colors.lightGray,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
    fontSize: 16,
  },
  comingSoonButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 40,
    paddingVertical: 14,
    borderRadius: 12,
    width: '100%',
  },
  comingSoonButtonText: {
    ...typography.button,
    color: colors.black,
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 16,
  },
  restDayNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.secondary + '15',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
    borderLeftWidth: 3,
    borderLeftColor: colors.secondary,
  },
  restDayNoteText: {
    ...typography.bodySmall,
    color: colors.lightGray,
    flex: 1,
    marginLeft: 8,
    lineHeight: 18,
  },
  restDayNoteTitle: {
    color: colors.secondary,
    fontWeight: 'bold',
  },
  workoutInProgressButton: {
    // LinearGradient handles the colors
  },
  noWorkoutCard: {
    backgroundColor: colors.darkGray,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
  },
  noWorkoutTitle: {
    ...typography.h3,
    color: colors.white,
    marginTop: 12,
    marginBottom: 8,
  },
  noWorkoutText: {
    ...typography.bodySmall,
    color: colors.lightGray,
    textAlign: 'center',
  },
  finishedWorkoutsButtonContainer: {
    borderRadius: 12,
    marginTop: 16,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  finishedWorkoutsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    padding: 16,
    gap: 12,
  },
  finishedWorkoutsButtonText: {
    ...typography.body,
    flex: 1,
    color: colors.black,
    fontWeight: 'bold',
  },
  videoSection: {
    marginBottom: 24,
  },
  videoContainer: {
    backgroundColor: colors.darkGray,
    borderRadius: 16,
    overflow: 'hidden',
    aspectRatio: 16/9,
    position: 'relative',
  },
  videoThumbnail: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.black,
    position: 'relative',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  videoPlayOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomBanner: {
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 90 : 82,
    left: 16,
    right: 16,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 20,
    zIndex: 1000,
  },
  bannerGradient: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(132, 204, 22, 0.3)',
    overflow: 'hidden',
  },
  blurContainer: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  bannerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 18,
    backgroundColor: 'rgba(15, 20, 30, 0.85)',
  },
  bannerLeft: {
    flex: 1,
    marginRight: 16,
  },
  bannerTitle: {
    ...typography.bodySmall,
    color: colors.primary,
    fontWeight: 'bold',
    fontSize: 11,
    letterSpacing: 1,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  bannerExerciseName: {
    ...typography.body,
    color: colors.white,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  bannerExerciseMeta: {
    ...typography.bodySmall,
    color: colors.lightGray,
    fontSize: 13,
    fontWeight: '500',
  },
  bannerRight: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  circularTimerContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    overflow: 'hidden',
  },
  circularTimerGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(132, 204, 22, 0.5)',
  },
  circularTimerText: {
    ...typography.body,
    color: colors.white,
    fontSize: 18,
    fontWeight: 'bold',
    fontVariant: ['tabular-nums'],
    marginBottom: 4,
  },
  circularPlayButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
});