import { StyleSheet } from 'react-native';
import { colors } from '@/constants/colors';
import { typography } from '@/constants/typography';

export const styles = StyleSheet.create({
    loadingContainer: {
        backgroundColor: colors.darkGray,
        borderRadius: 12,
        padding: 40,
        marginBottom: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        ...typography.body,
        color: colors.lightGray,
    },
    loadingSetsSkeleton: {
        backgroundColor: colors.darkGray,
        borderRadius: 8,
        padding: 30,
        marginVertical: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    container: {
        backgroundColor: colors.darkGray,
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
    },
    exerciseNameHeader: {
        marginBottom: 12,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.lightGray + '30',
    },
    exerciseName: {
        ...typography.h4,
        color: colors.white,
        fontWeight: '600',
        marginBottom: 4,
    },
    exerciseTarget: {
        ...typography.bodySmall,
        color: colors.lightGray,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    title: {
        ...typography.h5,
        color: colors.white,
    },
    subtitle: {
        ...typography.bodySmall,
        color: colors.lighterGray,
        marginTop: 2,
    },
    unitToggle: {
        flexDirection: 'row',
        gap: 8,
    },
    unitToggleRow: {
        marginBottom: 16,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    exerciseInfoRow: {
        flexDirection: 'row',
        gap: 16,
    },
    infoItem: {
        alignItems: 'center',
    },
    infoLabel: {
        fontSize: 12,
        color: colors.lightGray,
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    infoValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.white,
    },
    unitButton: {
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 8,
        backgroundColor: colors.mediumGray,
    },
    unitButtonActive: {
        backgroundColor: colors.primary,
    },
    unitButtonText: {
        ...typography.caption,
        color: colors.black,
    },
    tableHeader: {
        flexDirection: 'row',
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: colors.mediumGray,
        marginBottom: 8,
    },
    headerText: {
        ...typography.caption,
        color: colors.lightGray,
        textAlign: 'center',
    },
    setRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: colors.mediumGray,
    },
    setColumn: {
        width: '12%',
        alignItems: 'center',
    },
    weightColumn: {
        width: '37%',
        alignItems: 'center',
        marginHorizontal: 2,
    },
    repsColumn: {
        width: '37%',
        alignItems: 'center',
        marginHorizontal: 2,
    },
    checkboxColumn: {
        width: '14%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkbox: {
        width: 32,
        height: 32,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
    },
    checkboxChecked: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    setNumber: {
        ...typography.timerSmall,
        color: colors.white,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        height: 36,
        backgroundColor: colors.mediumGray,
        borderRadius: 8,
        paddingHorizontal: 4,
    },
    adjustButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: colors.darkGray,
        justifyContent: 'center',
        alignItems: 'center',
    },
    input: {
        ...typography.timerSmall,
        flex: 1,
        textAlign: 'center',
        color: colors.white,
    },
    inputDisabled: {
        opacity: 0.5,
    },
    actionsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
        marginTop: 12,
    },
    secondaryButton: {
        flex: 1,
        flexDirection: 'row',
        gap: 8,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.mediumGray,
        paddingVertical: 12,
        borderRadius: 10,
    },
    secondaryButtonText: {
        ...typography.button,
        color: colors.white,
    },
    disabledButton: {
        opacity: 0.5,
    },
    disabledField: {
        opacity: 0.5,
    },
    primaryButton: {
        flex: 1,
        backgroundColor: colors.primary,
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
    },
    primaryButtonText: {
        ...typography.button,
        color: colors.black,
    },
    completeButton: {
        flex: 1,
        backgroundColor: colors.success,
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
    },
    completeButtonText: {
        ...typography.button,
        color: colors.black,
    },
    completedButton: {
        backgroundColor: colors.mediumGray,
        opacity: 0.7,
    },
    completedButtonText: {
        color: colors.lightGray,
    },
    resetButton: {
        flex: 1,
        backgroundColor: colors.error,
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
    },
    resetButtonText: {
        ...typography.button,
        color: colors.white,
    },
    clearButton: {
        flex: 1,
        backgroundColor: colors.darkGray,
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.mediumGray,
    },
    clearButtonText: {
        color: colors.lighterGray,
        fontWeight: 'bold',
    },
    readOnlyBanner: {
        backgroundColor: colors.darkGray,
        borderRadius: 8,
        padding: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: colors.mediumGray,
    },
    readOnlyText: {
        ...typography.caption,
        color: colors.lighterGray,
        textAlign: 'center',
    },
    completedBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.darkGray,
        borderRadius: 8,
        padding: 12,
        marginBottom: 12,
        gap: 8,
        borderWidth: 1,
        borderColor: colors.success,
    },
    completedBannerText: {
        ...typography.body,
        color: colors.success,
        fontWeight: '600',
        fontSize: 16,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    modalContainer: {
        width: '85%',
        maxWidth: 400,
    },
    modalContent: {
        padding: 24,
        borderRadius: 16,
        alignItems: 'center',
    },
    modalTitle: {
        ...typography.h3,
        color: colors.white,
        marginBottom: 16,
        textAlign: 'center',
    },
    modalDescription: {
        ...typography.body,
        color: colors.lightGray,
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 22,
    },
    modalButtons: {
        display: 'flex',
        flexDirection: 'row',
        gap: 12,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalButton: {
        display: 'flex',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 48,
    },
    cancelButton: {
        backgroundColor: colors.mediumGray,
    },
    confirmButton: {
        backgroundColor: colors.primary,
    },
    cancelButtonText: {
        ...typography.button,
        color: colors.white,
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
    },
    confirmButtonText: {
        ...typography.button,
        color: colors.black,
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
    },
    singleButton: {
        flex: 0,
        minWidth: 120,
        maxWidth: 200,
    },
    dualButton: {
        flex: 0,
        minWidth: 120,
        maxWidth: 140,
    },
    prSection: {
        width: '100%',
        backgroundColor: colors.darkGray,
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: colors.primary,
    },
    prSectionTitle: {
        ...typography.body,
        color: colors.primary,
        fontWeight: '700',
        marginBottom: 12,
        textAlign: 'center',
    },
    prItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
        gap: 12,
    },
    prItemContent: {
        flex: 1,
    },
    prItemLabel: {
        ...typography.caption,
        color: colors.lightGray,
        fontSize: 12,
        marginBottom: 4,
    },
    prItemValue: {
        ...typography.body,
        color: colors.white,
        fontWeight: '600',
        fontSize: 16,
    },
    prItemPrevious: {
        ...typography.caption,
        color: colors.lighterGray,
        fontSize: 12,
        fontWeight: '400',
    },
    titleContainer: {
        flex: 1,
    },
    historyButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.darkGray,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        gap: 6,
    },
    historyButtonText: {
        ...typography.caption,
        color: colors.primary,
        fontWeight: '600',
    },
    suggestionsContainer: {
        backgroundColor: colors.darkGray,
        borderRadius: 12,
        padding: 12,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.primary,
    },
    suggestionsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
        gap: 8,
    },
    suggestionsTitle: {
        ...typography.body,
        color: colors.primary,
        fontWeight: '600',
        flex: 1,
    },
    suggestionsScroll: {
        flexGrow: 0,
    },
    suggestionChip: {
        backgroundColor: colors.mediumGray,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        marginRight: 8,
    },
    suggestionText: {
        ...typography.caption,
        color: colors.white,
        fontSize: 12,
    },
    completingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 9999,
    },
    completingContainer: {
        backgroundColor: colors.darkGray,
        borderRadius: 16,
        padding: 32,
        alignItems: 'center',
        borderWidth: 2,
        borderColor: colors.primary,
    },
    completingText: {
        ...typography.body,
        color: colors.primary,
        marginTop: 16,
        fontSize: 16,
        fontWeight: '600',
    },
    restTimerBanner: {
        marginVertical: 16,
        borderRadius: 12,
        overflow: 'hidden',
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    restTimerGradient: {
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(132, 204, 22, 0.3)',
        overflow: 'hidden',
    },
    restTimerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 14,
        paddingHorizontal: 16,
        backgroundColor: 'rgba(15, 20, 30, 0.85)',
    },
    restTimerLeft: {
        flex: 1,
    },
    restTimerTitle: {
        ...typography.bodySmall,
        color: colors.primary,
        fontWeight: 'bold',
        fontSize: 11,
        letterSpacing: 1,
        marginBottom: 2,
    },
    restTimerSubtext: {
        ...typography.caption,
        color: colors.lightGray,
        fontSize: 11,
    },
    restTimerRight: {
        alignItems: 'flex-end',
        gap: 4,
    },
    restTimerTime: {
        ...typography.h2,
        color: colors.white,
        fontSize: 28,
        fontWeight: 'bold',
    },
    restTimerSkip: {
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    restTimerSkipText: {
        ...typography.caption,
        color: colors.primary,
        fontSize: 11,
        fontWeight: '600',
    },
});