import { StyleSheet } from 'react-native';
import { colors } from '@/constants/colors';
import { typography } from '@/constants/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingSpinner: {
    marginBottom: 16,
  },
  loadingText: {
    ...typography.body,
    color: colors.lightGray,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.darkGray,
  },
  backButton: {
    marginRight: 16,
    padding: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 120, // Extra padding for floating button
  },
  workoutHeader: {
    marginBottom: 16,
  },
  weekIndicator: {
    ...typography.caption,
    color: colors.lightGray,
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  workoutName: {
    ...typography.h3,
    color: colors.white,
    marginBottom: 16
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.darkGray,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.mediumGray,
  },
  timerText: {
    ...typography.workoutTimer,
    color: colors.primary,
    textAlign: 'left',
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: 52,
  },
  timerTextInactive: {
    color: colors.lightGray,
  },
  timerTextComplete: {
    color: colors.success,
  },
  timerContainerInactive: {
    borderColor: colors.darkGray,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
  },
  timerContainerComplete: {
    borderColor: colors.success,
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
  },
  cardioTimerContent: {
    alignItems: 'flex-start',
  },
  timerLabel: {
    ...typography.caption,
    color: colors.lightGray,
    fontSize: 12,
    marginTop: -8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  timerControls: {
    flexDirection: 'row',
    gap: 8,
  },
  timerButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  playButton: {
    backgroundColor: colors.primary,
  },
  pauseButton: {
    backgroundColor: colors.primary,
  },
  resetButton: {
    backgroundColor: colors.mediumGray,
  },
  stopButton: {
    backgroundColor: colors.error,
  },
  workoutMeta: {
    flexDirection: 'row',
    gap: 16,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    fontSize: 14,
    color: colors.lightGray,
    textTransform: 'capitalize',
  },
  exercisesSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    ...typography.h3,
    color: colors.white,
    marginBottom: 16,
  },
  noExercisesText: {
    ...typography.body,
    color: colors.lightGray,
    textAlign: 'center',
    marginTop: 32,
  },
  exercisesSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    flexWrap: 'wrap',
    gap: 8,
  },
  addExerciseButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    gap: 4,
  },
  addExerciseButtonText: {
    ...typography.bodySmall,
    color: colors.black,
    fontWeight: 'bold',
  },
  maxCustomExercisesInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.mediumGray,
    gap: 8,
  },
  maxCustomExercisesText: {
    ...typography.bodySmall,
    color: colors.lightGray,
    fontStyle: 'italic',
  },
  addButtonsContainer: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    flexWrap: 'wrap',
    flexShrink: 0,
  },
  maxLimitReached: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  maxLimitText: {
    ...typography.bodySmall,
    color: colors.lightGray,
    fontStyle: 'italic',
  },
  addCardioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    gap: 4,
  },
  addCardioButtonText: {
    ...typography.bodySmall,
    color: colors.black,
    fontWeight: 'bold',
  },
  cardioSection: {
    marginTop: 24,
    marginBottom: 16,
  },
  cardioSectionTitle: {
    ...typography.h3,
    color: colors.white,
    marginBottom: 12,
  },
  cardioCard: {
    backgroundColor: colors.darkGray,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.mediumGray,
  },
  cardioCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  cardioCardInfo: {
    flex: 1,
  },
  cardioCardName: {
    ...typography.body,
    color: colors.white,
    fontWeight: '600',
    marginBottom: 4,
  },
  cardioCardDetails: {
    ...typography.bodySmall,
    color: colors.lightGray,
  },
  cardioCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  completedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 255, 136, 0.15)',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    gap: 4,
  },
  completedBadgeText: {
    ...typography.caption,
    color: colors.success,
    fontSize: 11,
    fontWeight: '600',
  },
  maxCardioInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.mediumGray,
    gap: 8,
  },
  maxCardioText: {
    ...typography.bodySmall,
    color: colors.lightGray,
    fontStyle: 'italic',
  },
  cardioSessionCard: {
    backgroundColor: colors.darkGray,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
    marginBottom: 16,
  },
  cardioSessionIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(76, 175, 80, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  cardioSessionText: {
    ...typography.body,
    color: colors.lightGray,
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 24,
  },
  progressBarContainer: {
    width: '100%',
    height: 8,
    backgroundColor: colors.mediumGray,
    borderRadius: 4,
    overflow: 'hidden',
    marginVertical: 16,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 4,
  },
  cardioSessionDetails: {
    marginTop: 20,
    width: '100%',
    gap: 12,
  },
  cardioDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
    borderRadius: 8,
  },
  cardioDetailText: {
    ...typography.body,
    color: colors.white,
    fontSize: 15,
    fontWeight: '600',
  },
  finishButton: {
    marginTop: 16,
    backgroundColor: colors.success,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  finishButtonText: {
    ...typography.button,
    color: colors.black,
  },
  
  // Modal styles
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  modalContainer: {
    width: '85%',
    maxWidth: 400,
  },
  modalContent: {
    padding: 24,
    borderRadius: 16,
    alignItems: 'center',
  },
  modalTitle: {
    ...typography.h3,
    color: colors.white,
    marginBottom: 16,
    textAlign: 'center',
  },
  modalDescription: {
    ...typography.body,
    color: colors.lightGray,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
  },
  modalButtons: {
    display: 'flex',
    flexDirection: 'row',
    gap: 12,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalButton: {
    display: 'flex',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  cancelButton: {
    backgroundColor: colors.mediumGray,
  },
  confirmButton: {
    backgroundColor: colors.primary,
  },
  cancelButtonText: {
    ...typography.button,
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  confirmButtonText: {
    ...typography.button,
    color: colors.black,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  singleButton: {
    flex: 0,
    minWidth: 120,
    maxWidth: 200,
  },
  dualButton: {
    flex: 0,
    minWidth: 120,
    maxWidth: 140,
  },
  startingWorkoutOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
  startingWorkoutContent: {
    backgroundColor: colors.darkGray,
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    gap: 16,
  },
  startingWorkoutText: {
    ...typography.body,
    color: colors.white,
    fontSize: 18,
    fontWeight: '600',
  },
  finishingOverlay: {
    flex: 1,
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  finishingContainer: {
    backgroundColor: colors.darkGray,
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    gap: 16,
  },
  finishingText: {
    ...typography.body,
    color: colors.white,
    fontSize: 18,
    fontWeight: '600',
  },
});