import { StyleSheet, Platform } from 'react-native';
import { colors } from '@/constants/colors';
import { typography } from '@/constants/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingTop: 0,
    paddingBottom: 32,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    gap: 12,
  },
  backButton: {
    padding: 4,
  },
  pageTitle: {
    ...typography.h2,
    color: colors.white,
    flex: 1,
  },
  section: {
    marginBottom: 24,
  },
  sectionLabel: {
    ...typography.body,
    color: colors.white,
    fontWeight: '600',
    marginBottom: 12,
  },
  input: {
    ...typography.body,
    backgroundColor: colors.mediumGray,
    borderRadius: 8,
    padding: 14,
    color: colors.white,
    fontSize: 16,
  },
  exercisesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  openPickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkGray,
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    borderWidth: 2,
    borderColor: colors.primary,
    borderStyle: 'dashed',
    gap: 8,
  },
  openPickerButtonText: {
    ...typography.body,
    color: colors.primary,
    fontWeight: '600',
    fontSize: 16,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
    backgroundColor: colors.darkGray,
    borderRadius: 12,
  },
  emptyStateText: {
    ...typography.body,
    color: colors.white,
    marginTop: 16,
    fontWeight: '600',
  },
  emptyStateSubtext: {
    ...typography.bodySmall,
    color: colors.lightGray,
    marginTop: 4,
  },
  exerciseCard: {
    backgroundColor: colors.mediumGray,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.darkGray,
  },
  exerciseCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  exerciseName: {
    ...typography.body,
    color: colors.white,
    fontWeight: '700',
    fontSize: 16,
    flex: 1,
  },
  removeButton: {
    padding: 4,
  },
  // Bottom Sheet Styles (Full Screen)
  bottomSheetContainer: {
    flex: 1,
    backgroundColor: colors.dark,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 12,
    backgroundColor: colors.darkGray,
    borderBottomWidth: 1,
    borderBottomColor: colors.mediumGray,
  },
  closeButton: {
    padding: 4,
    marginRight: 8,
  },
  sheetTitle: {
    ...typography.h2,
    color: colors.white,
    fontWeight: '700',
    flex: 1,
    fontSize: 20,
  },
  headerSpacer: {
    width: 32,
  },
  contentSection: {
    flex: 1,
    backgroundColor: colors.darkGray,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.mediumGray,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginHorizontal: 12,
    marginTop: 12,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    ...typography.body,
    color: colors.white,
    fontSize: 18,
  },
  categoryChipsContainer: {
    marginTop: 12,
    marginBottom: 6,
    maxHeight: 32,
  },
  categoryChipsContent: {
    paddingHorizontal: 12,
    gap: 8,
  },
  categoryChip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: colors.mediumGray,
    borderWidth: 1,
    borderColor: colors.mediumGray,
  },
  categoryChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  categoryChipText: {
    ...typography.bodySmall,
    color: colors.lightGray,
    fontWeight: '800',
  },
  categoryChipTextActive: {
    color: colors.black,
  },
  exerciseList: {
    flex: 1,
    marginTop: 4,
  },
  exerciseListContent: {
    paddingHorizontal: 12,
    paddingBottom: 100,
  },
  exerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.mediumGray,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  exerciseItemSelected: {
    backgroundColor: colors.darkGray,
    borderColor: colors.primary,
  },
  exerciseItemContent: {
    flex: 1,
    marginRight: 12,
  },
  exerciseItemName: {
    ...typography.body,
    color: colors.white,
    fontWeight: '900',
    fontSize: 18,
    marginBottom: 2,
  },
  exerciseItemMuscle: {
    ...typography.bodySmall,
    color: colors.lightGray,
    fontSize: 12,
  },
  emptyExerciseList: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyExerciseText: {
    ...typography.body,
    color: colors.white,
    fontWeight: '600',
    marginTop: 16,
  },
  emptyExerciseSubtext: {
    ...typography.bodySmall,
    color: colors.lightGray,
    marginTop: 4,
    textAlign: 'center',
  },
  floatingButtonContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    paddingBottom: Platform.OS === 'ios' ? 32 : 16,
    backgroundColor: colors.darkGray,
    borderTopWidth: 1,
    borderTopColor: colors.mediumGray,
  },
  floatingAddButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  floatingAddButtonText: {
    ...typography.button,
    color: colors.black,
    fontWeight: '700',
    fontSize: 16,
  },
  footer: {
    padding: 16,
    paddingBottom: Platform.OS === 'ios' ? 0 : 16,
    borderTopWidth: 1,
    borderTopColor: colors.darkGray,
  },
  saveButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    ...typography.button,
    color: colors.black,
    fontWeight: '700',
  },
});