import React, { useState } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
} from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { Feather as Icon } from "@expo/vector-icons";
import { colors } from "@/constants/colors";

// Import your boundaries to test them
import {
  WorkoutErrorBoundary,
  NutritionErrorBoundary,
  SubscriptionErrorBoundary,
} from "@/components/AppErrorBoundaries";

// A nasty component that crashes on purpose when told to
const Bomb = ({ shouldThrow }: { shouldThrow: boolean }) => {
  if (shouldThrow) {
    throw new Error(
      "This is a test error generated by the Error Boundary screen!"
    );
  }
  return null;
};

export default function ErrorBoundaryTestScreen() {
  const [crashType, setCrashType] = useState<string | null>(null);

  // If a crash is triggered, we render the Bomb inside the specific boundary
  if (crashType) {
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity
            onPress={() => setCrashType(null)}
            style={styles.backButton}
          >
            <Icon name="arrow-left" size={24} color="#FFF" />
            <Text style={styles.backText}>Reset</Text>
          </TouchableOpacity>
        </View>

        <View style={styles.crashContainer}>
          {crashType === "workout" && (
            <WorkoutErrorBoundary>
              <Bomb shouldThrow={true} />
            </WorkoutErrorBoundary>
          )}

          {crashType === "nutrition" && (
            <NutritionErrorBoundary>
              <Bomb shouldThrow={true} />
            </NutritionErrorBoundary>
          )}

          {crashType === "subscription" && (
            <SubscriptionErrorBoundary>
              <Bomb shouldThrow={true} />
            </SubscriptionErrorBoundary>
          )}
        </View>
      </View>
    );
  }

  return (
    <LinearGradient colors={["#1a1a1a", "#000"]} style={styles.container}>
      <ScrollView contentContainerStyle={styles.content}>
        <Icon
          name="alert-triangle"
          size={60}
          color={colors.primary}
          style={styles.icon}
        />
        <Text style={styles.title}>Error Boundary Tester</Text>
        <Text style={styles.subtitle}>
          Tap a button below to intentionally crash that part of the app and
          verify the error screen appears.
        </Text>

        <TouchableOpacity
          style={styles.button}
          onPress={() => setCrashType("workout")}
        >
          <Text style={styles.buttonText}>Trigger Workout Error</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.button}
          onPress={() => setCrashType("nutrition")}
        >
          <Text style={styles.buttonText}>Trigger Nutrition Error</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.button}
          onPress={() => setCrashType("subscription")}
        >
          <Text style={styles.buttonText}>Trigger Subscription Error</Text>
        </TouchableOpacity>
      </ScrollView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: 60 },
  content: { padding: 20, alignItems: "center" },
  crashContainer: { flex: 1, justifyContent: "center", padding: 20 },
  header: { paddingHorizontal: 20, marginBottom: 20 },
  backButton: { flexDirection: "row", alignItems: "center" },
  backText: { color: "#FFF", marginLeft: 10, fontSize: 16 },
  icon: { marginBottom: 20 },
  title: { fontSize: 24, fontWeight: "bold", color: "#FFF", marginBottom: 10 },
  subtitle: {
    fontSize: 16,
    color: "#ccc",
    textAlign: "center",
    marginBottom: 40,
  },
  button: {
    backgroundColor: "#333",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 12,
    width: "100%",
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#444",
    alignItems: "center",
  },
  buttonText: { color: "#FFF", fontSize: 16, fontWeight: "600" },
});
